models/topic.py
from models.orm_mongo import Mongo_ORM
from models.user import User


class Topic(Mongo_ORM):
    @classmethod
    def valid_names(cls):
        names = super().valid_names()
        names = names + [
            ('views', int, 0),
            ('title', str, ''),
            ('content', str, ''),
            ('user_id', int, 0),
            ('board_id', int, 0),
        ]
        return names

    @classmethod
    def get(cls, id):
        m = cls.find_by(id=id)
        m.views += 1
        m.save()
        return m

    def replies(self):
        from .reply import Reply
        ms = Reply.find_all(topic_id=self.id)
        return ms

    def board(self):
        from .board import Board
        m = Board.find(self.board_id)
        return m

    def user(self):
        u = User.find(id=self.user_id)
        return u

routes/reply.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.mail import Mail
from routes import *

from models.reply import Reply
from utils import log

main = Blueprint('reply', __name__)


def users_from_content(content):
    # 不能解决 @在文本中间 比如 123@name abc，这样就不能获得name了
    parts = content.split(' ')
    users = []
    for p in parts:
        if p.startswith('@'):
            username = p[1:]
            u = User.find_by(username=username)
            users.append(u)
    return users



def send_mails(sender, receivers, content):
    for r in receivers:
        form = dict(
            title='你被 {} AT 了'.format(r.username),
            content=content,
            sender_id=sender.id,
            receiver_id=r.id,
        )
        m = Mail.new(form)
        log(m)


@main.route("/add", methods=["POST"])
def add():
    log('reply add')
    form = request.form
    u = current_user()
    # 发邮件
    log('before send mail', form)
    content = form.get('content')
    log('reply', content)
    users = users_from_content(content)
    log('reply', users)
    send_mails(u, users, content)
    log('after send mail')
    m = Reply.new(form, user_id=u.id)
    return redirect(url_for('topic.detail', id=m.topic_id))

routes/topic.py
from flask import (
    Flask,
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    abort,
)
from datetime import datetime

from utils import *
from routes import *

from models.topic import Topic
from models.board import Board

main = Blueprint('topic', __name__)


@main.route("/")
def index():
    # board_id = 2
    # board_id = int(request.args.get('board_id', -1))
    # if board_id == -1:
    #     ms = Topic.all()
    # else:
    #     ms = Topic.find_all(board_id=board_id)
    # token = str(uuid.uuid4())
    # u = current_user()
    # csrf_tokens['token'] = u.id
    # bs = Board.all()
    # return render_template("topic/index2.html", ms=ms, token=token, bs=bs, bid=board_id)

    u = current_user()
    page_id = int(request.args.get('page_id', 1))
    board_id = int(request.args.get('board_id', -1))
    bs = Board.all()
    # log('csrf', csrf_tokens)

    if board_id != -1:
        ts = Topic.find_all(board_id=board_id)
        ps = None
    else:
        skip = (page_id - 1) * 20
        # log('skip', skip)
        ts = Topic.find_page_id(sk=skip, li=20)
        # log('ts', ts)
        ts_all = Topic.all()
        if len(ts_all) % 20 != 0:
            p = int((len(ts_all) / 20) + 1)
        else:
            p = int((len(ts_all) / 20))
        ps = list(range(1, p + 1))

    return render_template("topic/index.html", user=u, bid=board_id, bs=bs, ts=ts, ps=ps)


@main.route('/search')
def search():
    q = request.args.get('q', -1)
    log('q', q)

    if q == '':
        return redirect(url_for('.index'))
    else:
        ts = Topic.find_all(title={'$regex': q})
        return render_template("topic/index.html", ts=ts, ps=None)


@main.route('/<int:id>')
def detail(id):
    u = current_user()
    m = Topic.get(id)
    # log('m', m)
    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", user=u, topic=m)


@main.route('/add', methods=['POST'])
def add():
    u = current_user()
    form = request.form.to_dict()
    log('form', form)
    token = form.pop('token', -1)

    if token in csrf_tokens and csrf_tokens[token] == u.id:
        csrf_tokens.pop(token)
        if u is not None:
            m = Topic.new(form, user_id=u.id)
            return redirect(url_for('.detail', id=m.id))
    else:
        return url_for('.index')


@main.route('/delete')
def delete():
    id = int(request.args.get('id'))
    token = request.args.get('token')
    u = current_user()
    # 判断 token 是否是我们给的
    if token in csrf_tokens and csrf_tokens[token] == u.id:
        csrf_tokens.pop(token)
        if u is not None:
            # print('删除 topic 用户是', u, id)
            # Topic.delete(id)
            m = Topic.find_one(id=id)
            log('m', m)
            m.delete()
            return redirect(url_for('user.personal_index'))
        else:
            abort(403)
    else:
        abort(403)


@main.route("/new")
def new():
    u = current_user()
    board_id = int(request.args.get('board_id'))
    token = new_csrf_token()
    bs = Board.all()
    return render_template("topic/new.html", user=u, bs=bs, token=token, bid=board_id)

templates/topic/detail.html
{% extends "/base.html" %}
{% block content %}
<div id="main">
    <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
                <span class="topic_full_title">
                    <span class='put_top'>
                        {{ topic.board().title }}
                    </span>
                    <span style="margin-left: 6px;">
                        {{ topic.title }}
                    </span>
                </span>
                    <div class="changes">
                <span>
                    发布于 
                    {{ topic.timestamp() }}
                </span>
                <span>
                    作者
                    {{ topic.user().username }}
                </span>
                <span>
                浏览次数
                {{ topic.views }}
                </span>
                <span>
                来自
                {{ topic.board().title }}
                </span>
                </div>
            </div>

            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-text">
                        {{ topic.content|safe }}
                    </div>
                </div>
            </div>
        </div>
    <!--</div>-->

        <div class='panel'>
            <div class='header'>
                <span class='col_fade'>
                    <!-- 过滤器 -->
                    {{ topic.replies() | count }} 回复
                </span>
            </div>
            {% for r in topic.replies() %}
            <div class='cell reply_area reply_item'>
                <div class='author_content'>
                    <a href="/" class="user_avatar">
                        <img src="{{ r.user().user_image }}" alt="">
                    </a>
                    <div class='user_info'>
                        <a class='dark reply_author'>
                            {{ r.user().username }}
                        </a>
                        <a class="reply_time">
                            {{ loop.index }}楼
                             • {{ r.fromnow() }}
                        </a>
                    </div>
                    <div class='user_action'>
                        <span>
                            <i class="fa up_btn
                              fa-thumbs-o-up
                              invisible" title="喜欢"></i>
                            <span class="up-count">
                            </span>
                        </span>
                    </div>
                </div>
                <div class='reply_content from-leiwei1991'>
                    <div class="markdown-text">
                        {{ r.content }}
                    </div>
                </div>
            </div>
            {% endfor %}
            <!--</div>-->
        </div>

        {% if user %}
        <div class="panel">
            <div class="header">
                <span class="col_fade">添加回复</span>
            </div>
            <div class="inner reply">
                <form id="reply_form" action="{{ url_for('reply.add') }}" method="post">
                    <div class="markdown_editor in_editor">
                        <div class="markdown_in_editor">
                            <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                            <div class="editor_buttons">
                                <input class="span-primary submit_btn" type="submit" data-loading-text="回复中.." value="回复">
                            </div>
                        </div>
                    </div>
                    <input type="hidden" name="topic_id" id="_csrf" value="{{ topic.id }}">
                </form>
            </div>
        </div>
    {% endif %}
    </div>

    </div>
</div>
{% endblock %}

templates/topic/index.html
{% extends "base.html" %}
{% block content %}
    <div id="content">
        <div class="panel">
            <div id="tabSwitch" class="header">
                <a href="/topic" class="topic-tab">
                    全部
                </a>
                {% for b in bs %}
                <a href="/topic?board_id={{ b.id }}" class="topic-tab">
                    {{ b.title }}
                </a>
                {% endfor %}
            </div>

            <div class="inner no-padding">
                <div class="topic_list">
                    {% for topic in ts %}
                    <div class="cell">
                        <a class="user_avatar pull-left">
                            <img src="{{ topic.user().user_image }}">
                        </a>

                        <span class="reply_count pull-left">
                            <span class="count_of_replies" title="回复数">
                                {{ topic.replies() | count }}
                            </span>
                            <span class="count_seperator">/</span>
                            <span class="count_of_visits" title='点击数'>
                                {{ topic.views }}
                            </span>
                        </span>

                        <div class="topic_title_wrapper">
                            <span class='put_top'>
                                {{ topic.board().title }}
                            </span>

                            <a class="topic_title" href="{{ url_for('topic.detail', id=topic.id) }}">
                                {{ topic.title }}
                            </a>
                            <!--<span>{{ topic.replies() | count }} / {{ topic.views }}</span>-->
                            <!--<a class="topic_title" href="{{ url_for('topic.delete', id=topic.id, token=token) }}">-->
                            <!--删除-->
                            <!--</a>-->


                        <span class="last_time pull-right">
                            <span>
                                {{ topic.fromnow() }}
                            </span>
                            <!-- <span class="last_active_time">

                            </span> -->
                        </span>

                        </div>
                    </div>
                    {% endfor %}
                </div>

                <!--分页-->
                {% if ps %}
                <div class='pagination' current_page='1'>
                    <ul>
                        <li>
                            <a href="#">
                                «
                            </a>
                        </li>
                        {% for p in ps %}
                        <li>
                            <a href="{{ url_for('.index', page_id=p) }}">
                                {{ p }}
                            </a>
                        </li>
                        {% endfor %}
                        <li>
                            <a href="#">
                                »
                            </a>
                        </li>
                    </ul>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}
<!--<script>-->
<!--(function() {-->
<!--var editor = new Editor();-->
<!--editor.render($('.editor')[0]);-->
<!--})();-->
<!--</script>-->

templates/topic/new.html
{% extends "base.html" %}
{% block content %}
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
                        <fieldset>
                            <textarea autofocus class='span9' id='title' name='title' rows='1'
                                      placeholder="标题字数 6 字以上"></textarea>

                            <span class="tab-selector">选择版块：</span>
                            <select name="board_id" id="board" required>
                                {% for b in bs %}
                                    {% if bid == b.id %}
                                        <option value="{{ b.id }}" selected>{{ b.title }}</option>
                                    {% else %}
                                        <option value="{{ b.id }}">{{ b.title }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>

                            <div class='markdown_editor in_editor'>
                                <textarea id="text-input" class='editor' rows='20' oninput="this.editor.update()"
                                          placeholder="文章支持 Markdown 语法, 请注意标记代码"></textarea>
                                <textarea class="md-preview" name='content' style="display: none"></textarea>

                                <div class='editor_buttons'>
                                    <input type="submit" class='span-primary submit_btn' data-loading-text="提交中"
                                           value="提交">
                                </div>
                            </div>
                    </div>
                    <input type="hidden" name="token" value="{{ token }}">
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

{% block script %}
    {{ super() }}
    <script src="https://cdn.bootcss.com/markdown.js/0.5.0/markdown.min.js"></script>
    <script>
        function Editor(input, preview) {
            this.update = function () {
                preview.innerHTML = markdown.toHTML(input.value);
            };
            input.editor = this;
            this.update();
        }

        var $ = function (sel) {
            return document.querySelector(sel)
        };
        new Editor($("#text-input"), $(".md-preview"));
    </script>
{% endblock %}

templates/topic/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
                        <fieldset>
                            <textarea autofocus class='span9' id='title' name='title' rows='1' placeholder="标题字数 10 字以上"></textarea>
                            <div class='markdown_editor in_editor'>
                              <div class='markdown_in_editor'>
                                <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                <div class='editor_buttons'>
                                  <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
                                </div>
                              </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>

            <div class="panel">
        <div class="header">
          <span class="col_fade">添加回复</span>
        </div>
        <div class="inner reply">
          <form id="reply_form" action="/reply/add" method="post">

            <div class="markdown_editor in_editor">
              <div class="markdown_in_editor">
                <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                <div class="editor_buttons">
                  <input class="span-primary submit_btn" type="submit" data-loading-text="回复中.." value="回复">
                </div>
              </div>

            </div>

            <input type="hidden" name="topic_id" id="_csrf" value="3">
          </form>
        </div>
      </div>
        </div>
    </div>
<script>

  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>