models/user.py
# from models import Model
from models.orm_mongo import Mongo_ORM

Model = Mongo_ORM


class User(Model):
    """
    User 是一个保存用户数据的 model
    现在只有两个属性 username 和 password
    """

    @classmethod
    def valid_names(cls):
        names = super().valid_names()
        names = names + [
            ('username', str, ''),
            ('password', str, ''),
            ('signature', str, '这家伙很懒，什么个性签名都没有留下'),
            # ('user_image', str, '/uploads/default.png'),
            ('user_image', str, '/static/images/default.jpg'),
        ]
        return names

    def salted_password(self, password, salt='$!@><?>HUI&DWQa`'):
        import hashlib
        def sha256(ascii_str):
            return hashlib.sha256(ascii_str.encode('ascii')).hexdigest()

        hash1 = sha256(password)
        hash2 = sha256(hash1 + salt)
        return hash2

    def hashed_password(self, pwd):
        import hashlib
        # 用 ascii 编码转换成 bytes 对象
        p = pwd.encode('ascii')
        s = hashlib.sha256(p)
        # 返回摘要字符串
        return s.hexdigest()

    @classmethod
    def register(cls, form):
        name = form.get('username', '')
        pwd = form.get('password', '')
        if len(name) > 2 and User.find_by(username=name) is None:
            u = User.new(form)
            u.password = u.salted_password(pwd)
            u.save()
            return u
        else:
            return None

    @classmethod
    def validate_login(cls, form):
        u = User()
        u.username = form.get('username', '')
        u.password = form.get('password', '')
        user = User.find_by(username=u.username)
        if user is not None and user.password == u.salted_password(u.password):
            return user
        else:
            return None

routes/topic.py
from flask import (
    Flask,
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    abort,
)
from datetime import datetime

from utils import *
from routes import *

from models.topic import Topic
from models.board import Board

main = Blueprint('topic', __name__)


@main.route("/")
def index():
    # board_id = 2
    # board_id = int(request.args.get('board_id', -1))
    # if board_id == -1:
    #     ms = Topic.all()
    # else:
    #     ms = Topic.find_all(board_id=board_id)
    # token = str(uuid.uuid4())
    # u = current_user()
    # csrf_tokens['token'] = u.id
    # bs = Board.all()
    # return render_template("topic/index2.html", ms=ms, token=token, bs=bs, bid=board_id)

    u = current_user()
    page_id = int(request.args.get('page_id', 1))
    board_id = int(request.args.get('board_id', -1))
    bs = Board.all()
    # log('csrf', csrf_tokens)

    if board_id != -1:
        ts = Topic.find_all(board_id=board_id)
        ps = None
    else:
        skip = (page_id - 1) * 20
        # log('skip', skip)
        ts = Topic.find_page_id(sk=skip, li=20)
        # log('ts', ts)
        ts_all = Topic.all()
        if len(ts_all) % 20 != 0:
            p = int((len(ts_all) / 20) + 1)
        else:
            p = int((len(ts_all) / 20))
        ps = list(range(1, p + 1))

    return render_template("topic/index.html", user=u, bid=board_id, bs=bs, ts=ts, ps=ps)


@main.route('/search')
def search():
    q = request.args.get('q', -1)
    log('q', q)

    if q == '':
        return redirect(url_for('.index'))
    else:
        ts = Topic.find_all(title={'$regex': q})
        return render_template("topic/index.html", ts=ts, ps=None)


@main.route('/<int:id>')
def detail(id):
    u = current_user()
    m = Topic.get(id)
    # log('m', m)
    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", user=u, topic=m)


@main.route('/add', methods=['POST'])
def add():
    u = current_user()
    form = request.form.to_dict()
    log('form', form)
    token = form.pop('token', -1)

    if token in csrf_tokens and csrf_tokens[token] == u.id:
        csrf_tokens.pop(token)
        if u is not None:
            m = Topic.new(form, user_id=u.id)
            return redirect(url_for('.detail', id=m.id))
    else:
        return url_for('.index')


@main.route('/delete')
def delete():
    id = int(request.args.get('id'))
    token = request.args.get('token')
    u = current_user()
    # 判断 token 是否是我们给的
    if token in csrf_tokens and csrf_tokens[token] == u.id:
        csrf_tokens.pop(token)
        if u is not None:
            # print('删除 topic 用户是', u, id)
            # Topic.delete(id)
            m = Topic.find_one(id=id)
            log('m', m)
            m.delete()
            return redirect(url_for('user.personal_index'))
        else:
            abort(403)
    else:
        abort(403)


@main.route("/new")
def new():
    u = current_user()
    board_id = int(request.args.get('board_id'))
    token = new_csrf_token()
    bs = Board.all()
    return render_template("topic/new.html", user=u, bs=bs, token=token, bid=board_id)

routes/user.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    abort,
)

from routes import *

from models.reply import Reply
from models.user import User
from models.topic import Topic
from models.board import Board
from utils import log

main = Blueprint('user', __name__)


@main.route('/')
def personal_index():
    u = current_user()
    token = new_csrf_token()
    ts = Topic.find_all(user_id=u.id)

    rs = Reply.find_all(user_id=u.id)
    ts_id = []
    ts2 = []

    for r in rs:
        if r.topic_id not in ts_id:
            ts_id.append(r.topic_id)

    for id in ts_id:
        ms = Topic.find_all(id=id)
        for m in ms:
            if m not in ts2:
                ts2.append(m)

    return render_template('user/index.html', user=u, ts=ts, ts2=ts2, token=token)


@main.route('/<username>')
def user_index(username):
    log(username)
    # u = None
    # if username != '':
    #     u = User.find_by(username=username)
    # if u is None:
    #     u = current_user()
    # log('u', u.id)
    # ts = Topic.find_all(user_id=u.id)
    # log('ts', ts)
    # rs = Reply.find_all(user_id=u.id)
    #
    # ts_id = []
    # ts2 = []
    #
    # for r in rs:
    #     if r.topic_id not in ts_id:
    #         ts_id.append(r.topic_id)
    #
    # for id in ts_id:
    #     ms = Topic.find_all(id=id)
    #     for m in ms:
    #         if m not in ts2:
    #             ts2.append(m)
    #
    # log('ts2', ts2)
    return render_template('user/index.html', ts=ts)
    # return render_template("user/index.html", user=u, ts=ts, ts2=ts2)


@main.route('/setting', methods=['GET'])
def setting_get():
    u = current_user()
    token = new_csrf_token()
    return render_template('user/setting.html', user=u, token=token)


@main.route('/setting', methods=['POST'])
def setting_post():
    u = current_user()
    form = request.form
    # log('form', form)
    token = form.get('token', -1)

    if token in csrf_tokens and csrf_tokens[token] == u.id:
        csrf_tokens.pop(token)
        log('form', form)
        if u is not None:
            password = request.form.get('password', -1)
            if password != -1 and password != '':
                u.password = u.salted_password(password)

            signature = request.form.get('signature', -1)
            if signature != -1:
                u.signature = signature

            if password != -1 or signature != -1:
                u.save()
        return redirect(url_for('.setting_get'))

    else:
        return abort(403)

templates/user/index.html
{% extends "base.html" %}
{% block content %}
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="header">
                    <ul class="breadcrumb">
                        <li><a href="/user/">主页</a><span class="divider">/</span></li>
                    </ul>
                </div>
                <div class="inner userinfo">
                    <div class="user_big_avatar">
                        <img src="{{ user.user_image }}">
                    </div>
                    <a class="dark">
                        {{ user.username }}
                    </a>
                    <p class="col_fade">
                        注册时间：
                        {{ user.fromnow() }}
                    </p>
                </div>
            </div>

            <div class="panel">
                <div class="header">
                    <span class="col_fade">最近创建的话题</span>
                </div>

                <div class="inner no-padding">
                    <div class="topic_list">
                        {% for topic in ts %}
                            <div class="cell">
                                <!--<a class="user_avatar pull-left">-->
                                <!--<img src="{{ topic.user().user_image }}" title="avatar"/>-->
                                <!--</a>-->
                                <span class="reply_count pull-left">
                                <span class="count_of_replies" title="回复数">
                                    {{ topic.replies() | count }}
                                </span>
                                <span class="count_seperator">/</span>
                                <span class="count_of_visits" title='点击数'>
                                    {{ topic.views }}
                                </span>
                            </span>

                                <div class="topic_title_wrapper">
                                <span class='put_top'>
                                    {{ topic.board().title }}
                                </span>

                                    <a class="topic_title" href="{{ url_for('topic.detail', id=topic.id) }}">
                                        {{ topic.title }}
                                    </a>
                                    <!--<span>{{ topic.replies() | count }} / {{ topic.views }}</span>-->
                                    <a class="topic_title"
                                       href="{{ url_for('topic.delete', id=topic.id, token=token) }}">
                                        删除
                                    </a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

            <div class="panel">
                <div class="header">
                    <span class="col_fade">最近参与的话题</span>
                </div>

                <div class="inner no-padding">
                    <div class="topic_list">
                        {% for topic in ts2 %}
                            <div class="cell">
                                <!--<a class="user_avatar pull-left">-->
                                <!--<img src="{{ topic.user().user_image }}" title="avatar"/>-->
                                <!--</a>-->
                                <span class="reply_count pull-left">
                                <span class="count_of_replies" title="回复数">
                                    {{ topic.replies() | count }}
                                </span>
                                <span class="count_seperator">/</span>
                                <span class="count_of_visits" title='点击数'>
                                    {{ topic.views }}
                                </span>
                            </span>
                                <div class="topic_title_wrapper">
                                <span class='put_top'>
                                    {{ topic.board().title }}
                                </span>
                                    <a class="topic_title" href="{{ url_for('topic.detail', id=topic.id) }}">
                                        {{ topic.title }}
                                    </a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/login.html
{% extends "base.html" %}
{% block main %}
<div id='main'>
    <div id='sidebar'>
        <div class='panel'>
            <div class='header'>
                <span class='col_fade'>关于</span>
            </div>
            <div class='inner'>
                <p>专业中文社区</p>

                <p>在这里你可以：</p>
                <ul>
                    <li>向别人提出你遇到的问题</li>
                    <li>帮助遇到问题的人</li>
                    <li>分享自己的知识</li>
                    <li>和其它人一起进步</li>
                </ul>
            </div>
        </div>
    </div>

    <div id='content'>
        <div class='panel'>
            <div class='header'>
                <ul class='breadcrumb'>
                    <li><a href='/'>主页</a><span class='divider'>/</span></li>
                    <li class='active'>登录</li>
                </ul>
            </div>
            <div class='inner'>
                <form id='signin_form' class='form-horizontal' action='/login' method='post'>
                    <div class='control-group'>
                        <label class='control-label' for='name'>用户名</label>

                        <div class='controls'>
                            <input class='input-xlarge' id='name' name='username' placeholder="请输入用户名" size='30' type='text'/>
                        </div>
                    </div>
                    <div class='control-group'>
                        <label class='control-label' for='pass'>密码</label>

                        <div class='controls'>
                            <input class='input-xlarge' id='pass' name='password' placeholder="请输入密码" size='30' type='password'/>
                        </div>
                    </div>
                    <input type='hidden' name='_csrf' value='6l1W43XW-lsaW-Qm9jNepZYde-30F_zPVE-o'/>

                    <div class='form-actions'>
                        <input type='submit' class='span-primary' value='登录'/>
                        <a href="/auth/github">
                        <span class="span-info">
                          通过 GitHub 登录
                        </span>
                        </a>
                        <a id="forgot_password" href=''>忘记密码了?</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/user/register.html
{% extends "base.html" %}
{% block main %}
<div id='main'>
    <div id='sidebar'>
        <div class='panel'>
            <div class='header'>
                <span class='col_fade'>关于</span>
            </div>
            <div class='inner'>
                <p>专业中文社区</p>

                <p>在这里你可以：</p>
                <ul>
                    <li>向别人提出你遇到的问题</li>
                    <li>帮助遇到问题的人</li>
                    <li>分享自己的知识</li>
                    <li>和其它人一起进步</li>
                </ul>
            </div>
        </div>
    </div>

    <div id='content'>
        <div class='panel'>
            <div class='header'>
                <ul class='breadcrumb'>
                    <li><a href='/'>主页</a><span class='divider'>/</span></li>
                    <li class='active'>注册</li>
                </ul>
            </div>
            <div class='inner'>
                <form id='signin_form' class='form-horizontal' action='/register' method='post'>
                    <input style="display:none">
                    <div class='control-group'>
                        <label class='control-label' for='name'>用户名</label>

                        <div class='controls'>
                            <input class='input-xlarge' id='name' name='username' placeholder="请输入用户名" size='30' type='text'/>
                        </div>
                    </div>
                    <div class='control-group'>
                        <label class='control-label' for='pass'>密码</label>

                        <div class='controls'>
                            <input class='input-xlarge' id='pass' name='password' placeholder="请输入密码" size='30' type='password'/>
                        </div>
                    </div>
                    <input type='hidden' name='_csrf' value='6l1W43XW-lsaW-Qm9jNepZYde-30F_zPVE-o'/>

                    <div class='form-actions'>
                        <input type='submit' class='span-primary' value='注册'/>
                        <a href="/auth/github">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/user/setting.html
{% extends "base.html" %}
{% block content %}
<div id="main">
{#    <div id="sidebar">#}
{#        <div class="panel">#}
{#            <div class="header">#}
{#                <span class="col_fade">个人信息</span>#}
{#            </div>#}
{#            <div class="inner">#}
{#                <div class="user_card">#}
{#                    <div>#}
{#                        <a class="user_avatar" href="/user/gua">#}
{#                            <img src="{{ user.user_image }}" alt="">#}
{#                        </a>#}
{#                        <span class="user_name"><a class="dark" href="/user/gua">{{ user.username }}</a></span>#}
{#                        <div class="board clearfix">#}
{#                            <div class="floor">#}
{#                                <span class="big">签名:</span>#}
{#                            </div>#}
{#                        </div>#}
{#                        <div class="space clearfix"></div>#}
{#                        <span class="signature">{{ user.signature }}</span>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#        <div class="panel">#}
{#            <div class="inner">#}
{#                <a href="/topic/new?board_id=1" class="create_topic_btn">#}
{#                    <span class="span-success">发布话题</span>#}
{#                </a>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
    <div id="content">
        <div class="panel">
            <div class="header">
                <ul class="breadcrumb">
                    <li><a href="/user/">主页</a><span class="divider">/</span></li>
                    <li class="active">设置</li>
                </ul>
            </div>
            <div class="inner">
                <form id="setting_form" class="form-horizontal" action="/user/setting" method="post">
                    <div class="control-group">
                        <label class="control-label" for="name">用户名</label>
                        <div class="controls">
                            <input class="input-xlarge" id="name" name="username" value="{{ user.username }}" disabled size="30" type="text">
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="password">密码</label>
                        <div class="controls">
                            <input class="input-xlarge" id="password" name="password" placeholder="请输入新密码" size="30" type="password">
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="signature">个性签名</label>
                        <div class="controls">
                            <input class="input-xlarge" id="name" name="signature" value="{{ user.signature }}" size="30" type="text">
                        </div>
                    </div>

                    <input type="hidden" name="token" value="{{ token }}">

                    <div class="form-actions">
                        <input type="submit" class="span-primary submit_btn" data-loading-text="保存中.." value="保存设置">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- <script>
    $(document).ready(function() {
        $('.follow_btn').click(function() {
            var $me = $(this);
            var action = $me.attr('action');
            var params = {
                follow_id: '5996badeee602e88524b439a',
                _csrf: 'N6RFcJIO-hChj9Mrclu6xbIZ8abPuwE70K-I'
            };
            $.post('/user/' + action, params, function(data) {
                if (data.status === 'success') {
                    var $btns = $('.follow_btn');
                    if (action === 'follow') {
                        $btns.html('取消关注');
                        $btns.attr('action', 'un_follow');
                    } else {
                        $btns.html('加入关注');
                        $btns.attr('action', 'follow');
                    }
                    $btns.toggleClass('btn-success');
                }
            }, 'json');
        });
    });
</script> -->
{% endblock %}